language: "pt"

pipeline:
  - name: "nlp_spacy"
    model: "pt"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_crf"
  - name: "ner_synonyms"